FROM webdevops/php-apache:8.0-alpine

# 首先配置 vhost
COPY vhost.conf /opt/docker/etc/httpd/vhost.conf
# COPY web.vhost.conf /opt/docker/etc/httpd/vhost.common.d/

# 然后运行初始化脚本
# https://dockerfile.readthedocs.io/en/latest/content/Customization/provisioning.html
COPY init.sh /opt/docker/provision/entrypoint.d/
#CMD chmod +x /opt/docker/provision/entrypoint.d/init.sh
ADD supervisord-proxy.conf /opt/docker/etc/supervisor.d/prism-proxy.conf

EXPOSE 80 
EXPOSE 8802

